### PR TITLE
Create ModelHub support

### PR DESCRIPTION
**Pull request by drraymond27**

### CODE REVIEW

**Comment by drraymond27** [comment]
@DirtyRacer1337 How I can edit the failed py?

**Comment by drraymond27** [comment]
@DirtyRacer1337 OK, I don't know why the PR merge to this repertory, and I can't merge to PAHelper, the desktop confuse me.

**Comment by DirtyRacer1337** [comment]
Where did you get that xpaths, none of them works

**Comment by drraymond27** [comment]
> Where did you get that xpaths, none of them works

I copied the from ManyVids, 🥺

**Comment by DirtyRacer1337** [comment]
OK, I got you don't even tested it

**Comment by drraymond27** [comment]
@DirtyRacer1337 sorry, I have to learn more about this, better let this to the experts for now.

**Pull request closed without merging**
