### PR TITLE
FTV: Improve Name Handling | 18 Only Girls: Switch to Google Search

### PR DESCRIPTION
**Pull request by bigbadwolfie**
There is no way to identify actresses based on the search since the site only gives the first name.

This is probably something that can be maintained as duplicates are found. I could not think a better way to manage it other than manually tagging scenes with their galleries.

### CODE REVIEW

**Comment by DirtyRacer1337** [comment]
Use [PAactors.py](https://github.com/DirtyRacer1337/PhoenixAdult.bundle/blob/e2c90b75930a7149133c9d7f3cf51d6a4f1d892a/Contents/Code/PAactors.py#L239), for models

**Comment by bigbadwolfie** [comment]
The issue is though I have no way to identify if I use PAactors without the sceneID. At least I can't find anything that would work.

Example
https://ftvmilfs.com/update/ryan-226.html - Ryan Ryans
https://ftvmilfs.com/update/ryan-210.html - Ryan Keely

**Comment by DirtyRacer1337** [comment]
That's problem then, they have full name only on description I think I can extract it

**Comment by bigbadwolfie** [comment]
That would work in these two cases, but then it fails in other cases where the last name is never mentioned in the description. That's why I figured hard coding by sceneID would be the method of least resistance.

https://www.ftvgirls.com/update/alex-and-nina-1585.html - Alex Legend/Nina North
https://www.ftvgirls.com/update/alex-1524.html Alex

**Comment by DirtyRacer1337** [comment]
So at least if name exist it will be grabbed, better than make it manually. I updated second method, to not grab your last examples

**Comment by bigbadwolfie** [comment]
Fixed this as well PAhelper#1086

**Pull request merged**
