### PR TITLE
Dorcel Club Site Change Fix

### PR DESCRIPTION
**Pull request by freeloaderfreddie**
Issue #10 
All images other than movie posters are blurred in the new site design. The new code will only download movie posters, it won't search for scene images.

### CODE REVIEW

**Comment by freeloaderfreddie** [comment]
Just realized the new search is not limited. You can use more than the title. We should change the site list doc.

**Comment by freeloaderfreddie** [comment]
@DirtyRacer1337 can you do that or should I create another PR?

**Comment by DirtyRacer1337** [comment]
Did that in e2c90b75930a7149133c9d7f3cf51d6a4f1d892a

**Comment by dsrtusr88** [comment]
> 
> 
> Issue #10
> All images other than movie posters are blurred in the new site design. The new code will only download movie posters, it won't search for scene images.

We had this issue in the last code base that was noticed:
This is an image if you're not a subscriber:
https://public16-content.dorcelclub.com/pics/gallery/12/85/11285_1_gallery0_1_596_396_fb-b8_db024004.webp
This is the same image if you're logged in:
https://public16-content.dorcelclub.com/pics/gallery/12/85/11285_1_gallery0_1_596_396_fb_da153288.webp

Both are public facing, I'm not sure what the code fix was that allowed it to pull the unblurred vs the good images.

**Comment by dsrtusr88** [comment]
@freeloaderfreddie @DirtyRacer1337 
This was the fix in the last code base, the url referenced above can be shortened with 'scenedefault.jpg' on the end.

image

**Comment by DirtyRacer1337** [comment]
@dsrtusr88 did that in c6c3973fd9c5a0f54b44311a7b8ffff5d2cabb97
@freeloaderfreddie why you rewrite all my old code, you can just update xpath?

**Pull request merged**
